# Generated by Django 4.2 on 2023-10-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pics/'),
        ),
    ]
