# Generated by Django 4.2 on 2023-10-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='loginback.png', null=True, upload_to='pics'),
        ),
    ]
